# Ref: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  persistence:
    enabled: false
  adminUser: admin
  adminPassword: admin
  grafana.ini:
    server:
      protocol: http
      http_port: 3000
      domain: localhost
      serve_from_sub_path: false
    smtp:
      enabled: false
  ingress:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki:3100

# Ref: https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
loki:
  fullnameOverride: loki
  config:
    server:
      http_listen_port: 3100

# Ref: https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
promtail:
  fullnameOverride: promtail
  config:
    lokiAddress: http://loki:3100/loki/api/v1/push