grafana:
  enabled: true
  persistence:
    enabled: false
  grafana.ini:
    server:
      protocol: http
      http_port: 3000
      domain: localhost
      serve_from_sub_path: false
    smtp:
      enabled: false
    security:
      disable_initial_admin_creation: false
      admin_user: admin
      admin_password: admin
  ingress:
    enabled: false